biology = input("Please enter your Biology marks: ")
chemistry = input("Please enter your Chemistry marks: ")
physics = input("Please enter your Physics marks: ")
total = int(biology) + int(chemistry) + int(physics)
average = float(total/3)
print('Your average score is: ')
print(round(average,2))
